import './globals.css'
import type { Metadata } from 'next'
import { Providers } from './providers'
import { Header } from '../components/header'

export const metadata: Metadata = {
  title: 'Ramá Business',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        {/* <Image
          src="/rama-fundo.jpeg"
          alt="fundo rama"
          layout="fill"
          objectFit="cover"
          quality="100"
          // objectPosition="center"
          className="opacity-20"
        /> */}
        <Providers>
          <Header />
          <main>{children}</main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  )
}
