import './globals.css'
import type { Metadata } from 'next'
import { Providers } from './providers'
import { Header } from '../components/header'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'Ramá Business',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        {/* <Image
          layout="fill"
          objectFit="fill"
          objectPosition="center"
          className="opacity-40"
          src="/yellow-background.jpg"
          alt="fundo rama"
        /> */}
        <Providers>
          <Header />
          <main>{children}</main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  )
}
