import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { Header } from '../components/header'
import Image from 'next/image'
// import {Poppins} from 'next/font/google'

// const poppins = Poppins({
//   subsets: ['latin'],
//   variable: '--font-poppins',
//   weight: '400'
// })

export const metadata: Metadata = {
  title: 'Ramá Business',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        {/* <Image
          layout='fill'
          objectFit='cover'
          objectPosition='center'
          className='opacity-10'
          src='/rama.jpeg'
          alt='fundo rama'
        /> */}
        <Providers >
          <Header />
          <main>{children}</main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  )
}


